Add sensor module to test environment and test script for it
HTD-Health/ai-smart-mirror pull request #12
Opened 2021-02-13 17:47 UTC by jedrzejpolaczek

2021-02-15 07:15 UTC, KonradNojman requested changes
Great to have the sensor in our test setup! 🚀 
For the sake of just testing the sensor out, I think this code is enough. I spotted only one change that needs to be made. The rest looks ok 👍

2021-02-15 07:15 UTC, KonradNojman commented on src/sensors/sensors_tests/HC-SR04/HC-SR04_simple_test.py
> +            time.sleep(0.0001)                           # wait 10 microseconds (10us HIGH pulse)
10 microseconds is 0.00001s. I believe sensor docs said the pulse to be **at least 10us**, so should work anyways. But we could change the value to match the actual pulse width.
```suggestion
            time.sleep(0.00001)                           # wait 10 microseconds (10us HIGH pulse)
```

2021-02-15 07:17 UTC, KonradNojman commented
As I understand this code is just until we have the other code for the sensor ready and merged to `main`, right @jedrzejpolaczek?

2021-02-15 15:54 UTC, GrivIN requested changes
event bus move should not be a part of this PR

2021-02-15 15:56 UTC, GrivIN commented on src/sensors/sensors_tests/HC-SR04/HC-SR04_simple_test.py
> +    except KeyboardInterrupt:
this exception should be handeled outsige this function

2021-02-15 15:56 UTC, GrivIN commented on src/sensors/sensors_tests/HC-SR04/HC-SR04_simple_test.py
> +            print('in: %0.2f\tcm: %0.2f' % (inches, cm))
instead of print is should be returned

2021-02-15 15:57 UTC, GrivIN commented on src/sensors/sensors_tests/HC-SR04/HC-SR04_simple_test.py
> +            while GPIO.input(echo_pin) == 0:             # wait for input from echo. if LOW record time
while not GPIO.input(echo_pin)

2021-02-15 15:59 UTC, GrivIN commented on src/sensors/sensors_tests/HC-SR04/HC-SR04_simple_test.py
> +	run_hc_sr04(trigger_pin, echo_pin)
actually there is a way to do that with callbacks: https://sourceforge.net/p/raspberry-gpio-python/wiki/Inputs/

2021-02-15 16:46 UTC, jedrzejpolaczek commented on src/sensors/sensors_tests/HC-SR04/HC-SR04_simple_test.py
> +            time.sleep(0.0001)                           # wait 10 microseconds (10us HIGH pulse)
Thanks for your remark!
To answer your question: it is only a script for testing how the sensor is working or how to work with the sensor. I don't think it will be a part of the final solution for the sensor module.

2021-02-15 16:53 UTC, jedrzejpolaczek commented on src/sensors/sensors_tests/HC-SR04/HC-SR04_simple_test.py
> +    except KeyboardInterrupt:
True, will be fixed in next commit.

2021-02-15 16:56 UTC, jedrzejpolaczek commented on src/sensors/sensors_tests/HC-SR04/HC-SR04_simple_test.py
> +            while GPIO.input(echo_pin) == 0:             # wait for input from echo. if LOW record time
For educational purposes, I would leave it as it is. I think it easier to understand what's going on when we have a representation of low voltage as 0 and high voltage as 1 in `if` conditions. What do you think?

2021-02-15 16:56 UTC, jedrzejpolaczek commented on src/sensors/sensors_tests/HC-SR04/HC-SR04_simple_test.py
> +	run_hc_sr04(trigger_pin, echo_pin)
For educational purposes, I would leave it as it is. I agree the final solution should use it.

2021-02-15 17:03 UTC, jedrzejpolaczek commented on src/sensors/sensors_tests/HC-SR04/HC-SR04_simple_test.py
> +            print('in: %0.2f\tcm: %0.2f' % (inches, cm))
Fixed in the commit 1ad441e

2021-02-21 22:27 UTC, KonradNojman commented on src/sensors_tests/HC-SR04/HC-SR04_simple_test.py
> +        sys.exit(0)
Maybe we can move this part to the `finally` block, so it runs for any other potential exception as well? What do you think?

2021-02-21 22:27 UTC, KonradNojman approved these changes

2021-02-21 22:48 UTC, jedrzejpolaczek commented on src/sensors_tests/HC-SR04/HC-SR04_simple_test.py
> +        sys.exit(0)
Good point!

2021-02-21 22:50 UTC, merged