Add distance sensor code and example data
HTD-Health/ai-smart-mirror pull request #2
Opened 2021-02-01 08:57 UTC by KonradNojman

Added code and results from tests with the distance sensor.

Todo:
- rewrite code to a more up to date version
- consider a format of the returned data and what API sensor functions should have

2021-02-01 16:18 UTC, rpoltorak reviewed
Awesome job, love it! Wish to test it later on hardware :)
Regarding comments: I would consider using a linter + formatter to prevent most of the issues that I've found. Anyway, we should create a separate issue for that thing.

2021-02-01 16:18 UTC, rpoltorak commented on sensors/distance-sensor/distance-sensor.py
> +print "Ultrasonic Measurement"
As we'd like to use Python3, let's change it to
`print("Ultrasonic Measurement")`

2021-02-01 16:18 UTC, rpoltorak commented on sensors/distance-sensor/distance-sensor.py
> +            elapsed = stop-start
I would change that that into:
`elapsed = stop - start`

anyway, should be checked and fixed automatically by formatter

2021-02-01 16:18 UTC, rpoltorak commented on sensors/distance-sensor/distance-sensor.py
> +            print "Distance :", distance
Same here (`print()`) and few lines below

2021-02-02 00:08 UTC, jedrzejpolaczek requested changes
TODO:
1. Switch solution to python 3.7
2. Add logic to measure over and over again after X seconds.
3. Sync solution with @GrivIN event bus (after it would be merged). If the distance is less then Y, send a signal through the event bus.
My proposition to keep parameters X and Y in the separate config file.

In general greater work!

2021-02-02 11:16 UTC, azjawinski requested changes
Great job! Included few optimization-related comments, and many unnecessary math equations 😄

2021-02-02 11:16 UTC, azjawinski commented on sensors/distance-sensor/distance-sensor.py
> +            distance = round(distancet / 2, 2)
1. Quick optimization hack: instead of doing
`distance = (elapsed * 34300) / 2` 
each time we can include this division in the constant (because multiplication is commutative):
```
SPEED_OF_SOUND = 34300  # cm/s
HALF_SPEED_OF_SOUND = SPEED_OF_SOUND / 2

distance = elapsed * HALF_SPEED_OF_SOUND
```

2. Let's restrict the CPU usage by introducing a simple time sampling for Echo measuring, as probably we do not need a perfect precision.

Quick math: 
`distance = duration * 17150`
Substituting duration for our TIME_PRECISION we get the precision of measured distance (of course with some variations, but should be close), 
e.g. for TIME_PRECISION = 0.0001:
`distance_precision = 0.0001 * 17150 = 1.715  #cm`

===================================================================

Comparing with the current solution (where `time()` takes the role of a frequency limiter):
`python -mtimeit -s'import time' 'time.time()'`
for me gave: `5000000 loops, best of 5: 87 nsec per loop`
i.e. 0,000000087 s
i.e. precision of 0,00149205 cm

`python -mtimeit -s'import time' 'time.sleep(0.0001)'`
for me gave: `2000 loops, best of 5: 132 usec per loop`
i.e.  0.000132 s
i.e. precision of 2,2638 cm

===================================================================

Also I've checked how stable is sampling done this way, quick results:
Run `sleep(0.0001)` 10 times (which should take about 0.001s)
`python -mtimeit -n 10 -r 20 -u sec -v -s'import time' 'time.sleep(0.0001)'`
```
raw times: 0.00129 sec, 0.00128 sec, 0.00128 sec, 0.00131 sec, 0.0013 sec, 0.00129 sec, 0.00132 sec, 0.00131 sec, 0.00127 sec, 0.0013 sec, 0.0013 sec, 0.00128 sec, 0.00131 sec, 0.00129 sec, 0.0013 sec, 0.00135 sec, 0.00131 sec, 0.00127 sec, 0.00128 sec, 0.00135 sec

10 loops, best of 20: 0.000127 sec per loop
```

===================================================================
Example code:
```
SPEED_OF_SOUND = 34300  # cm/s
HALF_SPEED_OF_SOUND = SPEED_OF_SOUND / 2
TIME_PRECISION = 0.0001  # s

while GPIO.input(GPIO_ECHO)==0:
    time.sleep(TIME_PRECISION)
echo_start = time.time()

while GPIO.input(GPIO_ECHO)==0:
    time.sleep(TIME_PRECISION)
echo_stop = time.time()

pulse_duration = echo_stop - echo_start
distance = round(pulse_duration * HALF_SPEED_OF_SOUND, 2)
```

2021-02-02 11:16 UTC, azjawinski commented on sensors/distance-sensor/distance-sensor.py
> +        print "Unexpected Error"
Catching everything is always risky. Even if we want to do it like that and print (for current mvp, probably later have a separate logger instance connected to the event bus) probably we should include the type of exception at least.

2021-02-07 15:47 UTC, jedrzejpolaczek commented on sensors/distance-sensor/distance-sensor.py
> +#!/usr/bin/python
Proposition for file structure: let move it to module folder so we will have a structure like this
module
|->camera
|->even_bus
|->distance_sensor

etc.

2021-02-15 16:31 UTC, jedrzejpolaczek requested changes
Really nice work with rewriting code to Python 3!
 Unfortunately, I think we weren't on the same page last time because two points from the previous review are still missing:
1. Add logic to measure over and over a gain after X seconds.
2. Sync solution with @GrivIN event bus (after it would be merged). If the distance is less then Y, send a signal through the event bus.
And also config file is missing.

To be honest, we can skip point 2 (only add TODO comment in proper place) in this PR.

2021-02-15 16:31 UTC, jedrzejpolaczek commented on module/distance_sensor/distance_sensor.py
> +# Use BCM GPIO references
Nice comment (could be in one line)!

2021-02-15 16:31 UTC, jedrzejpolaczek commented on module/distance_sensor/distance_sensor.py
> +            print("Distance :", distance)
Proposition: we can make it on one line like

> Ultrasonic Measurement - Distance: X cm

Or something like that. We can use it to see how the module is working. I think print's in other parts of the code can stay only for debugging purposes.

2021-02-15 16:31 UTC, jedrzejpolaczek commented on module/distance_sensor/distance_sensor.py
> +
Here we need to add a condition under what distance we decide to send a signal that something is afront mirror.
Brake point distance value should be loaded from config file.
Sending signal should be done by using the event bus. For this PR we can only add TODO comment.

2021-02-15 16:31 UTC, jedrzejpolaczek commented on module/distance_sensor/distance_sensor.py
> +with open('distance.csv', mode='w') as csv_file:
I think we do not need storing data in CSV file.

2021-02-15 16:31 UTC, jedrzejpolaczek commented on module/distance_sensor/distance_sensor.py
> +import RPi.GPIO as GPIO
It would be nice to run the whole solution from `if  __name__ == "__main__"` block.

2021-02-15 16:31 UTC, jedrzejpolaczek commented on module/distance_sensor/distance_sensor.py
> +# Import required Python libraries
Really nice comments to the code!

2021-02-15 16:31 UTC, jedrzejpolaczek commented on module/distance_sensor/distance_sensor.py
> +    try:
Nice use of `try-except` block!

2021-02-15 16:31 UTC, jedrzejpolaczek commented on module/distance_sensor/distance_sensor.py
> +            echo_start = time.time()
Optimization ;) Nice move here.

2021-02-15 16:31 UTC, jedrzejpolaczek commented on module/distance_sensor/distance_sensor.py
> +
It always worth to clean GPIO, even hear.

2021-02-15 17:01 UTC, jedrzejpolaczek commented on module/distance_sensor/distance_sensor.py
> +                time.sleep(TIME_PRECISION)
I do not think sleep is needed here.

2021-02-15 17:11 UTC, jedrzejpolaczek commented on module/distance_sensor/distance_sensor.py
> +#!/usr/bin/python
Quick proposition: what you say to rename `module` to `modules` and move `modules` to `src`?
In that way we can keep all code in src, code of modules like `HC-SR04` or `even bus` code in modules and some utility code in src.

2021-02-15 22:23 UTC, jedrzejpolaczek commented on module/distance_sensor/distance_sensor.py
> +GPIO.cleanup()
My proposition about event bus solution is to broadcasting distance as a float value. It may look like this:
```
topic_distance = 10001  # should be loaded from file

# Create socket on where we will be producing signals
    zmq_context = zmq.Context()
    produce_socket = zmq_context.socket(zmq.PUB)

    # Connect to event bus server to send
    produce_socket.connect(event_bus_server_ip, ":%s" % sending_port)

    # Create object to pack data
    data_packer = xdrlib.Packer()

    # Pack topic filter for distance into a buffer to be able to catch it from incoming messages
    data_packer.pack_uint(topic_distance)

# Pack topic and file name to send
                data_packer.pack_uint(topic_distance)
                data_packer.pack_string(image_file_name)
                
                print('BROADCASTING TOPIC: ', topic_distance, " WITH VALUE: ", distance)

                # Send data
                produce_socket.send(data_packer.get_buffer())
                data_packer.reset()
```

2021-02-19 17:28 UTC, KonradNojman commented on module/distance_sensor/distance_sensor.py
> +# Define GPIO to use on Pi
we are waiting for the proposed way of placing this consts and configs, so we can update it when it's ready

2021-02-21 22:21 UTC, KonradNojman commented on module/distance_sensor/distance_sensor.py
> +
For the simplicity sake we will send all readouts to the event bus, to be handled by the other module/controller. We can add some logic here later if needed.

2021-02-21 22:22 UTC, KonradNojman commented on module/distance_sensor/distance_sensor.py
> +#!/usr/bin/python
done. We can discuss if we want to have some specific naming convention for the sensor folders. Shouldn't be to many of them, so I don't think it will be an issue.

2021-02-22 11:52 UTC, azjawinski approved these changes

2021-02-22 11:52 UTC, azjawinski commented on src/modules/distance_sensor/distance_sensor.py
> +        echo_start = time.time()
Probably writing this as a class could help to avoid globals.

2021-02-22 11:52 UTC, azjawinski commented on src/modules/distance_sensor/distance_sensor.py
> +def run_ultrasonic_sensor(trigger_pin, echo_pin):
Maybe `measure_distance`?
`Run sensor` for me suggests that we use it to run the loop, while here we trigger only a single measurement and return the distance.

Also if written as a class we could avoid this arg passing and have a simple `self.TRIGGER_PIN`

2021-02-22 11:52 UTC, azjawinski commented on src/modules/distance_sensor/distance_sensor.py
> +    # @TODO: Decide how to pass Pins - via console arguments or Consts from the config file.
We aim to use Docker everywhere, so the config should come from ENV variables rather than a config file - exactly as you have done it below.

2021-02-22 12:46 UTC, KonradNojman commented on src/modules/distance_sensor/distance_sensor.py
> +    # @TODO: Decide how to pass Pins - via console arguments or Consts from the config file.
Great, thanks!

2021-02-22 12:48 UTC, KonradNojman commented on src/modules/distance_sensor/distance_sensor.py
> +        echo_start = time.time()
hmm, I'll look into that. Sounds like a good idea that didn't come up when I was searching how to tackle this callback problem. I only considered globals and lambdas 🚀

2021-02-24 00:43 UTC, jedrzejpolaczek requested changes
Great work. Only a little polish with docstrings and we are ready to go!

2021-02-24 00:43 UTC, jedrzejpolaczek commented on src/modules/distance_sensor/distance_sensor.py
> +        # Send pulse to trigger
Minor thing, docstrings in Python used to be like that (one of variation):
"""Docstring
    
    Args:
        input_string (str): string in JSON schema containing input.
    Raises:
        KeyError: blablabla raise when blablabla
    Returns:
       (str): converted input string with new ending.
"""

2021-02-24 00:43 UTC, jedrzejpolaczek commented on src/modules/distance_sensor/distance_sensor.py
> +# Consts that don't need to be set from the outside
Hard coding these values forcing us to change values in the code. Normally I would agree on that approach but this project is a little R&D and probably will be in need to change these values to experiment with hardware.

2021-02-24 00:43 UTC, jedrzejpolaczek commented on src/modules/distance_sensor/distance_sensor.py
> +SPEED_OF_SOUND = 34300  # cm/s
A little TODO for later: move this variables to a place where the whole logic will be and add the speed of sound in inches.

2021-02-24 00:43 UTC, jedrzejpolaczek commented on src/modules/distance_sensor/results/distance_walk_from_the_side.csv
> +time,distance
CSV files are unnecessary.

2021-02-24 08:50 UTC, KonradNojman commented on src/modules/distance_sensor/distance_sensor.py
> +            data_packer.reset()
Self note: 
Send a distance to the event bus only if smaller than a threshold (from env)

2021-02-24 08:55 UTC, KonradNojman commented on src/modules/distance_sensor/distance_sensor.py
> +# Consts that don't need to be set from the outside
@jedrzejpolaczek Did you have a problem with those values when setting up your sensor? 
Speed of sound is a physical const.
Trigger pulse time is set based on the sensor documentation, so I don't think we will change it.

Sensor settle time I agree we might want to change when we add some code and it's not sufficient for some reason.

2021-02-24 08:56 UTC, KonradNojman commented on src/modules/distance_sensor/distance_sensor.py
> +SPEED_OF_SOUND = 34300  # cm/s
Can you elaborate on why we would want to have the speed of sound in inches? Do we base our code on imperial units?

2021-02-24 08:59 UTC, KonradNojman commented on src/modules/distance_sensor/results/distance_walk_from_the_side.csv
> +time,distance
They were created as sample readouts of the sensor for other devs so they could simulate the distance sensor in their features. Do you think at this point it won't be useful anymore and we should remove those files from the repo?

2021-02-24 14:38 UTC, jedrzejpolaczek commented on src/modules/distance_sensor/distance_sensor.py
> +SPEED_OF_SOUND = 34300  # cm/s
(just an idea to discuss) Calculating distance is a part of the logic so it would be a good idea to move them to the module where all logic based on sensor readings sensor is. But this will be part of another issue after we decide if we need to have ECU or not.

2021-02-24 14:38 UTC, jedrzejpolaczek commented on src/modules/distance_sensor/results/distance_walk_from_the_side.csv
> +time,distance
tbh it just pops into my mind that maybe we can use them as a sample of readings from the sensor for the cases when we need to test something, not in the test environment. For that that will be very useful but may be prepared in the way like:
- CSV file when something is approaching
- CSV file when something is moving away
- CSV file when something is approaching and after that moving away

What do you think?

2021-02-24 17:25 UTC, KonradNojman commented on src/modules/distance_sensor/results/distance_walk_from_the_side.csv
> +time,distance
this is exactly what they are. We have 2 CSVs with (i hope) descriptive names of the action that user did. And the graphs in this PR description are based on those CSVs as well. The images in the /results/ directory have the same name to visualize how this data looks like.
I would suggest leaving it as is or moving it somewhere else just in case someone needs to use this data. And if we have everything ready we could remove those files if needed 🤔 . 
And we can discuss it in this PR or change/remove it in the other one as well of course

2021-02-24 23:22 UTC, jedrzejpolaczek commented on src/modules/distance_sensor/distance_sensor.py
> +#!/usr/bin/python
Just a little remark: we do not need this line due to our architecture solution based on docker's. Explanation: https://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take

2021-02-28 21:28 UTC, KonradNojman commented on src/modules/distance_sensor/distance_sensor.py
> +        # Send pulse to trigger
Added docstrings in [54474d5](https://github.com/HTD-Health/ai-smart-mirror/pull/2/commits/54474d589a27d4282d2cf930e2ea456e0e32430b). Please check if they are sufficient :)

2021-03-01 09:12 UTC, jedrzejpolaczek approved these changes

2021-03-01 09:16 UTC, merged